#!/usr/bin/env python3
"""
Bulk RAG Metadata Creation Script

This script reads batch files generated by create_rag_jurisdiction_metadata.py
and processes them by invoking the create_rag_metadata MCP tool for each entry.

Usage:
    python3 bulk_create_rag_metadata.py [--batch-dir DIR] [--start-from FILE] [--limit N]

Options:
    --batch-dir DIR   Directory containing batch JSON files (default: ../assets)
    --start-from FILE Start processing from a specific batch file
    --limit N         Process only N entries total (for testing)
    --verify          Enable immediate verification after each creation
    --dry-run         Show what would be done without invoking tools
"""

import json
import sys
import os
import glob
import argparse
from typing import List, Dict, Any


def load_batch_files(batch_dir: str, start_from: str = None) -> List[str]:
    """Load and sort batch files from the given directory."""
    pattern = os.path.join(batch_dir, "rag_meta_batch_*.json")
    files = sorted(glob.glob(pattern))
    
    if not files:
        print(f"No batch files found in {batch_dir}")
        sys.exit(1)
    
    if start_from:
        start_index = None
        for i, f in enumerate(files):
            if os.path.basename(f) == start_from:
                start_index = i
                break
        if start_index is None:
            print(f"Warning: {start_from} not found, starting from beginning")
        else:
            files = files[start_index:]
    
    return files


def load_entries(batch_file: str) -> List[Dict[str, Any]]:
    """Load entries from a batch file."""
    with open(batch_file, 'r') as f:
        data = json.load(f)
    return data.get('files', [])


def process_entry(entry: Dict[str, Any], dry_run: bool = False, verify: bool = False) -> bool:
    """
    Process a single entry by checking existing metadata and then creating or updating.
    
    Returns True if successful, False otherwise.
    """
    rag_file_name = entry.get('ragFileName')
    entries = entry.get('entries', [])
    
    if not rag_file_name or not entries:
        print(f"  ERROR: Invalid entry - missing ragFileName or entries")
        return False
    
    jurisdiction_code = None
    for e in entries:
        if e.get('key') == 'jurisdiction_code':
            jurisdiction_code = e.get('valueStr')
            break
    
    if dry_run:
        print(f"  DRY RUN: Would check/create/update metadata for {rag_file_name}")
        print(f"  DRY RUN:   jurisdiction_code = {jurisdiction_code}")
        return True
    
    try:
        # 1. Check Existing Metadata
        print(f"  Checking metadata for: {rag_file_name}")
        # TODO: Replace with actual MCP tool call
        # current_meta = CallMcpTool(server_name="orca", tool_name="list_rag_metadata", arguments={"ragFileName": rag_file_name})
        
        # Simulate check logic for now (in real implementation, parse current_meta)
        # For this simulation, we assume it's missing to trigger creation logic or just log
        print(f"  Action: Creating/Updating metadata for {rag_file_name} with value {jurisdiction_code}")
        
        # 2. Decision Logic (Simulated)
        # If key missing -> create_rag_metadata
        # If key exists & same -> skip
        # If key exists & different -> update_rag_metadata
        
        # TODO: Replace with actual MCP tool call
        # result = CallMcpTool(server_name="orca", tool_name="create_rag_metadata", arguments=entry)
        
        if verify:
            print(f"  Verifying metadata for: {rag_file_name}")
            # TODO: Replace with actual verification call
            # verify_result = CallMcpTool(server_name="orca", tool_name="list_rag_metadata", arguments={"ragFileName": rag_file_name})
    except Exception as e:
        print(f"  ERROR: Exception during metadata processing: {e}")
        return False
    
    return True


def generate_report(processed: int, failed: int, total: int, output_file: str = None):
    """Generate a summary report of the processing."""
    report = {
        "summary": {
            "total_entries": total,
            "processed": processed,
            "failed": failed,
            "remaining": total - processed - failed,
            "success_rate": f"{(processed / total * 100):.2f}%" if total > 0 else "N/A"
        }
    }
    
    if output_file:
        with open(output_file, 'w') as f:
            json.dump(report, f, indent=2)
        print(f"\nReport saved to: {output_file}")
    
    return report


def main():
    parser = argparse.ArgumentParser(
        description='Bulk create RAG metadata from batch files'
    )
    parser.add_argument(
        '--batch-dir',
        default='/Users/jiangzhaohua/codes/visdom/skills/orca/assets',
        help='Directory containing batch JSON files'
    )
    parser.add_argument(
        '--start-from',
        help='Start processing from a specific batch file (e.g., rag_meta_batch_2.json)'
    )
    parser.add_argument(
        '--limit',
        type=int,
        help='Process only N entries total (for testing)'
    )
    parser.add_argument(
        '--verify',
        action='store_true',
        help='Enable immediate verification after each creation'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be done without invoking tools'
    )
    parser.add_argument(
        '--report',
        default='bulk_processing_report.json',
        help='Output file for the processing report'
    )
    
    args = parser.parse_args()
    
    # Load batch files
    batch_files = load_batch_files(args.batch_dir, args.start_from)
    print(f"Found {len(batch_files)} batch files to process")
    
    # Count total entries
    total_entries = 0
    for batch_file in batch_files:
        entries = load_entries(batch_file)
        total_entries += len(entries)
    
    print(f"Total entries to process: {total_entries}")
    
    if args.limit:
        print(f"Limiting to {args.limit} entries")
    
    # Process entries
    processed = 0
    failed = 0
    limit = args.limit or total_entries
    
    for batch_file in batch_files:
        if processed >= limit:
            break
        
        print(f"\nProcessing: {os.path.basename(batch_file)}")
        entries = load_entries(batch_file)
        
        for entry in entries:
            if processed >= limit:
                break
            
            success = process_entry(
                entry,
                dry_run=args.dry_run,
                verify=args.verify
            )
            
            if success:
                processed += 1
            else:
                failed += 1
            
            # Progress indicator
            if (processed + failed) % 10 == 0:
                print(f"  Progress: {processed}/{min(limit, total_entries)} processed")
    
    # Generate report
    print(f"\n{'='*60}")
    print("PROCESSING COMPLETE")
    print(f"{'='*60}")
    print(f"Total processed: {processed}")
    print(f"Failed: {failed}")
    print(f"Remaining: {total_entries - processed - failed}")
    
    report = generate_report(
        processed=processed,
        failed=failed,
        total=total_entries,
        output_file=os.path.join(args.batch_dir, args.report)
    )
    
    print(f"\nSuccess rate: {report['summary']['success_rate']}")


if __name__ == "__main__":
    main()
